// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorRisk.Infrastructure.Persistence.PostgreSql;

#nullable disable

namespace VendorRisk.Infrastructure.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20260111222207_CreateTable")]
    partial class CreateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendorRisk.Domain.Entities.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessedat");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risklevel");

                    b.Property<decimal>("RiskScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("riskscore");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendorid");

                    b.HasKey("Id")
                        .HasName("pk_riskassessments");

                    b.HasIndex("AssessedAt");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_riskassessments_vendorid");

                    b.HasIndex("VendorId", "AssessedAt");

                    b.ToTable("RiskAssessments", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.VendorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FinancialHealth")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("financialhealth");

                    b.Property<int>("MajorIncidents")
                        .HasColumnType("integer")
                        .HasColumnName("majorincidents");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SecurityCerts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("securitycerts");

                    b.Property<decimal>("SlaUptime")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("slauptime");

                    b.HasKey("Id")
                        .HasName("pk_vendorprofiles");

                    b.HasIndex("Name");

                    b.ToTable("VendorProfiles", (string)null);
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.RiskAssessment", b =>
                {
                    b.HasOne("VendorRisk.Domain.Entities.VendorProfile", "Vendor")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.VendorProfile", b =>
                {
                    b.OwnsOne("VendorRisk.Domain.Common.DocumentStatus", "Documents", b1 =>
                        {
                            b1.Property<int>("VendorProfileId")
                                .HasColumnType("integer");

                            b1.Property<bool>("ContractValid")
                                .HasColumnType("boolean")
                                .HasColumnName("ContractValid");

                            b1.Property<bool>("PentestReportValid")
                                .HasColumnType("boolean")
                                .HasColumnName("PentestReportValid");

                            b1.Property<bool>("PrivacyPolicyValid")
                                .HasColumnType("boolean")
                                .HasColumnName("PrivacyPolicyValid");

                            b1.HasKey("VendorProfileId");

                            b1.ToTable("documentstatus");

                            b1.WithOwner()
                                .HasForeignKey("VendorProfileId");
                        });

                    b.Navigation("Documents")
                        .IsRequired();
                });

            modelBuilder.Entity("VendorRisk.Domain.Entities.VendorProfile", b =>
                {
                    b.Navigation("RiskAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
